- name: enable epel repository
  yum:
    name: http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-5.noarch.rpm
    state: present

- name: install self-access dotfiles
  copy:
    src: "{{ item }}"
    dest: /root/.{{ item }}
  with_items:
  - wgetrc
  - curlrc

- name: install nginx
  yum:
    name: nginx
    state: latest

- name: copy nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: dork.nginx reload

- name: copy proxy config
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
  notify: dork.nginx reload

- name: generate default vhost
  template:
    src: default.conf.j2
    dest: /etc/nginx/conf.d/default.conf
  notify: dork.nginx reload

- name: get stat of /var/web
  stat:
    path: /var/web
  register: dir

- name: link /var/source directly to /var/web
  file:
    src: /var/source
    dest: /var/web
    state: link
  when: not dir.stat.exists

- name: supervisor configuration
  copy:
    src: nginx.ini
    dest: /etc/supervisord.d/nginx.ini
  register: nginx_ini

- name: reload supervisor
  shell: supervisorctl reload
  when: nginx_ini.changed
