- name: install self-access dotfiles
  copy:
    src: "{{ item }}"
    dest: /root/.{{ item }}
  with_items:
  - wgetrc
  - curlrc

- name: install nginx
  yum:
    name: nginx
    state: latest

- name: copy nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: dork.nginx reload

- name: copy proxy config
  template:
    src: proxy.conf.j2
    dest: /etc/nginx/conf.d/proxy.conf
  notify: dork.nginx reload

- name: generate static asset host
  template:
    src: static.conf.j2
    dest: /etc/nginx/conf.d/static.conf
  when: nginx_http_port
  notify: dork.nginx reload

- name: remove static asset host
  file:
    path: /etc/nginx/conf.d/static.conf
    state: absent
  when: not nginx_http_port
  notify: dork.nginx reload

- name: get stat of /var/web
  stat:
    path: /var/web
  register: dir

- name: link /var/source directly to /var/web
  file:
    src: /var/source
    dest: /var/web
    state: link
  when: not dir.stat.exists

- name: supervisor configuration
  copy:
    src: nginx.ini
    dest: /etc/supervisord.d/nginx.ini

- name: start nginx
  supervisorctl:
    name: nginx
    state: started
